// BridgeLogHandler.swift

#if os(Android)

import Logging

/// Forwards Swift logs to Kotlin via JNI. Kotlin side writes to Logcat.
struct BridgeLogHandler: LogHandler {
    // `SwiftPokemonBridgeJava` (generated by @JavaClass) is not Sendable. Safe here:
    // bridgeRef is immutable, set once at init.
    let bridgeRef: SwiftPokemonBridgeJava

    var metadata: Logger.Metadata = [:]
    var logLevel: Logger.Level = .info

    subscript(metadataKey key: String) -> Logger.Metadata.Value? {
        get { metadata[key] }
        set { metadata[key] = newValue }
    }

    func log(level: Logger.Level,
             message: Logger.Message,
             metadata: Logger.Metadata?,
             source: String,
             file: String,
             function: String,
             line: UInt) {
        let text = "[\(level)] [\(source)] \(message)"
        if level >= .error {
            let fileName = file.split(separator: "/").last.map(String.init) ?? file
            let errorSource = "\(source)/\(fileName):\(line)"
            bridgeRef.logError(errorSource, text)
        } else {
            bridgeRef.logMessage(text)
        }
    }
}

#endif // os(Android)
