// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: pokemon.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct PB_Pokemon: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: Int32 = 0

  public var name: String = String()

  public var spriteURL: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct PB_PokemonListState: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var pokemons: [PB_Pokemon] = []

  public var lastRefreshEpochMs: Int64 = 0

  public var loadState: PB_PokemonListState.LoadState = .idle

  /// Pre-formatted, user-facing label like "Last refresh: Apr 23, 14:32". Formed in the
  /// shared VM so the UI (iOS/Android) just renders it — no duplicated locale logic.
  public var lastRefreshLabel: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum LoadState: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case idle // = 0
    case loading // = 1
    case loaded // = 2
    case failed // = 3
    case UNRECOGNIZED(Int)

    public init() {
      self = .idle
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .idle
      case 1: self = .loading
      case 2: self = .loaded
      case 3: self = .failed
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .idle: return 0
      case .loading: return 1
      case .loaded: return 2
      case .failed: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [PB_PokemonListState.LoadState] = [
      .idle,
      .loading,
      .loaded,
      .failed,
    ]

  }

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "sample.pokemon.v1"

extension PB_Pokemon: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Pokemon"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}name\0\u{3}sprite_url\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.spriteURL) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.id != 0 {
      try visitor.visitSingularInt32Field(value: self.id, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if !self.spriteURL.isEmpty {
      try visitor.visitSingularStringField(value: self.spriteURL, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: PB_Pokemon, rhs: PB_Pokemon) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.name != rhs.name {return false}
    if lhs.spriteURL != rhs.spriteURL {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension PB_PokemonListState: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PokemonListState"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}pokemons\0\u{3}last_refresh_epoch_ms\0\u{3}load_state\0\u{3}last_refresh_label\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.pokemons) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.lastRefreshEpochMs) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.loadState) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.lastRefreshLabel) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.pokemons.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.pokemons, fieldNumber: 1)
    }
    if self.lastRefreshEpochMs != 0 {
      try visitor.visitSingularInt64Field(value: self.lastRefreshEpochMs, fieldNumber: 2)
    }
    if self.loadState != .idle {
      try visitor.visitSingularEnumField(value: self.loadState, fieldNumber: 3)
    }
    if !self.lastRefreshLabel.isEmpty {
      try visitor.visitSingularStringField(value: self.lastRefreshLabel, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: PB_PokemonListState, rhs: PB_PokemonListState) -> Bool {
    if lhs.pokemons != rhs.pokemons {return false}
    if lhs.lastRefreshEpochMs != rhs.lastRefreshEpochMs {return false}
    if lhs.loadState != rhs.loadState {return false}
    if lhs.lastRefreshLabel != rhs.lastRefreshLabel {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension PB_PokemonListState.LoadState: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0IDLE\0\u{1}LOADING\0\u{1}LOADED\0\u{1}FAILED\0")
}
